### ISSUE TITLE
org.jboss.marshalling and org.jboss.marshalling.river Modules Broken in 7.1.3 Build

### ISSUE THREAD

**Issue by joshuaswett** [hasalex/eap-build#113]
While testing the EAP 7.1.3 build result, I ran into an issue at runtime with the org.jboss.marshalling module.  Here is the relevant bit of the stacktrace:

> Caused by: java.lang.ClassNotFoundException: sun.misc.Unsafe from [Module "org.jboss.marshalling" from local module loader @345965f2 (finder: local module finder @429bd883

This issue is happening because the eap7 build downloads version 3.0.10.Final of the wildfly-core sources (which contain the module.xml definition for the org.jboss.marshalling and org.jboss.marshalling.river modules), but the pom.xml for core-feature-pack is explicitly replaced by the 3.0.16.Final-redhat-1 version.  wildfly-core 3.0.10.Final pins jboss marshalling 2.0.2.Final and wildfly-core 3.0.16.Final-redhat-1 pins jboss marshalling 2.0.5.Final-redhat-1.  Some code changes in this newer version of jboss marshalling require the module.xml to declare a dependency on sun.jdk, but since the module.xml from wildfly-core 3.0.10.Final is being used, this change to the module.xml is not present.

I was able to fix this issue by adding the following dependency to both the org.jboss.marshalling and org.jboss.marshalling.river module.xml files living under modules/system/layers/base/org/jboss/marshalling (this may or may not be the same thing that is present in wildfly-core version 3.0.16.Final-redhat-1):
```xml
<module name="sun.jdk"/>
```

It is my understanding that the build has to use wildfly-core version 3.0.10.Final sources because the sources for 3.0.16.Final-redhat-1 are not available, and swapping in the core-feature-pack pom.xml from version 3.0.16.Final-redhat-1 is the best that can be done to align versions appropriately.  The one pitfall is the scenario described above where you run into an incompatibility between the src in the core-feature-pack and dependency versions from the swapped-in pom.xml.

I suppose fixing incompatibilities like this could be achieved by the build process by applying patches to the sources before building as is done in the EAP 6 builds.

**Comment by hasalex** [comment]
Good test ans great diagnostic. Thanks Joshua.

The patches in EAP 6 was annoying me, it made it more difficult to setup a new version.
As the change occurs only in a XML file, I'll try to fix it with sed or something like that.

**Comment by hasalex** [comment]
Hi Joshua,
Could you explain how you reproduce the bug, please.
I would like to enhance the tests in the build.

**Comment by joshuaswett** [comment]
Alexis,

The way I reproduce the issue currently has quite a few floating variables -- I am in the process of testing out what we need to do to migrate our application from EAP 6 to 7, so the standalone.xml I'm using has a lot of additional stuff in it and our application is not the simplest deployment in the world.  I'm trying to come up with a more minimal example and so far I haven't had any luck, but I will give you what I can right now.

What I currently believe to be the path for reproducing the issue is basically just having Infinispan set up to cache your web sessions (this is configured by default in the distrubuted standalone.xml).  Here is the specific configuration I'm using when this issue is happening (non-web caches have been omitted):

> <subsystem xmlns="urn:jboss:domain:infinispan:4.0">
    <cache-container name="web" aliases="standard-session-cache" default-cache="local-web" module="org.jboss.as.clustering.web.infinispan">
        <local-cache name="local-web">
            <transaction mode="BATCH"/>
            <file-store passivation="false" purge="false"/>
        </local-cache>
    </cache-container>
</subsystem>

The actual issue is showing up when Infinispan (SingleFileStore.java) is trying to write the session to the cache and jboss.marshalling is utilized for serialization.  The initialization of the org.jboss.marshalling.river.RiverMarshaller f
[stacktrace.txt]
ails because there is a sun/misc/Unsafe field which results in a ClassNotFoundException.

Here is the full stack trace I am getting during the error, which shows the involvement of Undertow, Infinispan, and JBoss Marshalling: (https://github.com/hasalex/eap-build/files/2246164/stacktrace.txt)

**Comment by joshuaswett** [comment]
I now have a simple way to replicate this issue: All that you need to do is try to construct an instance of a org.jboss.marshalling.river.RiverMarshaller from within a deployment.  The deployment must declare module dependencies on org.jboss.marshalling.river and org.jboss.marshalling.

I am attaching a [WAR archive](https://github.com/hasalex/eap-build/files/2249873/marshalling-bug.war.zip) which does this and will reproduce the issue on a vanilla EAP 7.1.3 build using the default standalone.xml configuration.  All you need to do is deploy the WAR and navigate to localhost:8080/marshalling-bug in your browser.  The JSP will throw the error I have previously described.

If you then "fix" the module.xml files for JBoss marshalling by adding a dependency on sun.jdk, the error no longer happens.

**Comment by hasalex** [comment]
I've just pushed a commit to fix your issue.
I'll let you close the issue if it's fine.

Thanks a lot for your contribution;

**Comment by joshuaswett** [comment]
Fix verified.  Thanks!
