### ISSUE TITLE
can't find 6.1.1 maven repo

### ISSUE THREAD

**Issue by mlybarger** [hasalex/eap-build#118]
awesome project.  i want to build from source eap 6.1.1.  this tool looks like it can really help! however, i can't find the 6.1.1 maven repo. any help on where to dl that?

**Comment by hasalex** [comment]
The 6.1.1 version is the older one that we can easily support with the current script.
Please pull the latest version and launch `./build-eap6.sh 6.1.1`.

**Comment by mlybarger** [comment]
i get an error building 6.1.1.  i'm missing dependencies.  i'll attach the log.

[build.log](https://github.com/hasalex/eap-build/files/2453906/build.log)

**Comment by hasalex** [comment]
The missing dependency is built at previous step of the process.
So there's no serious reason to miss it, except the lack of consistency of maven.

I would suggest to launch the build again and tell me if you have the same error.

**Comment by mlybarger** [comment]
odd. i would have thought that if the dependency were built at a previous step, it would have found it in my local repo.  

at any rate, i was able to build after re-running the build again.  thanks for your help.
