### ISSUE TITLE
EAP 7.2.0 Build Failure

### ISSUE THREAD

**Issue by dheerajarora** [hasalex/eap-build#122]
Hi, 

I'm building EAP 7.2.0 and I'm getting following error and maven build gets failed.

> [INFO] --- galleon-maven-plugin:2.0.1.Final:provision (server-provisioning) @ wildfly-dist ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35.459 s
[INFO] Finished at: 2019-04-24T08:46:00+05:30
[INFO] Final Memory: 120M/579M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jboss.galleon:galleon-maven-plugin:2.0.1.Final:provision (server-provisioning) on project wildfly-dist: Failed to provision the state: Failed to determine the latest version of org.jboss.universe:community-universe:jar:[0.0,) -> [Help 1]

Any pointers would be a great help, thanks

**Comment by hasalex** [comment]
Unfortunately, I've never encountered this problem.
Could you tell me a bit more about your build ?
* What's your OS ?
* Did you launch `./build-eap7.sh 7.2.0` ?
* With the latest revision of the script ?
* Did you launch it once or several times ?

**Comment by dheerajarora** [comment]
Please see the details below:

    What's your OS ?  -- Ubuntu 18.4
    Did you launch ./build-eap7.sh 7.2.0 ?  -- Yes
    With the latest revision of the script ?  -- Yes
    Did you launch it once or several times ?  -- Several times

Apart from the above, following is some more env specific details.
java version "**1.8.0_201**"
Apache Maven **3.6.0**

I tried to build the server again from the latest script and made it to fetch all the maven dependencies again and it worked, I tried twice. I'm taking it as some problem with my local maven repo coz rest everything is same except the local maven repo.

Thanks

**Comment by hasalex** [comment]
I like your explanation. 
Some corrupted files in the maven repository could break the build. If the same error occurs again, try just to delete the files of the artefact in error.
