### ISSUE TITLE
Sed -i with no argument will not work for BSD sed

### ISSUE THREAD

**Issue by natedennis** [hasalex/eap-build#132]

**Comment by hasalex** [comment]
Hi Nathan,
Your fix produces a new backup file.
Is there a way to avoid that ? Or to generate it in the work/ directory ?

**Comment by natedennis** [comment]
I dont believe so with the -i option. Some versions of sed is allowing you to leave the extension blank ... just not making the backup and editing in place. i guess theres a couple options here..  do the work in the work directory instead of the download directory or remove the file after it is generated. or i suppose rethink what we are doing with sed and not use the -i option.

**Comment by hasalex** [comment]
You're right. I should avoid the -i option, as it's not standard.
I'll merge your PR and think about it later.
Thanks.
