### ISSUE TITLE
Redhat Trademark

### ISSUE THREAD

**Issue by cher1705** [hasalex/eap-build#135]
Hi,
first of all, thanks for the great job you did! And honestly my issue isn't a coding one just an informative.
Our aim is to switch to your solution because of licensing stuff and so on but, what to tell Redhat, if they want us, to scan our network. Do they know, that we are using your solution / our own JBossEAP or do they just see that's a RH-JBossEAP?

Also you wrote "The result isn't exactly a JBoss EAP binary but something with a few differences."
Can I see those differences somewhere? Because, actually I already created some binaries for different JBossEAP Versions like 6.4.22 or 7.2.4 and by the latter one, there is no difference in the boot up log output. In both versions the RedHat one and my own one, I see 
"JBoss EAP 7.2.4.GA (WildFly Core 6.0.16.Final-redhat-00002)". So what am I asking for myself is, are still the RedHat trademarks available?

Kind Regards

**Comment by fcorneli** [comment]
See also:
https://github.com/hasalex/eap-build/issues/69
https://github.com/hasalex/eap-build/issues/41

**Comment by cher1705** [comment]
Thank you @fcorneli
