### ISSUE TITLE
build error eap-6.3.3

### ISSUE THREAD

**Issue by sanindd** [hasalex/eap-build#139]
Good day! Can't build version 6.3.3. not available url - http://repo.maven.apache.org/maven2/org/apache/felix/maven-bundle-p                                                     lugin/2.3.7/maven-bundle-plugin-2.3.7.pom
The problem is in the protocol HTTP. By https it works! 
Where can I change the link to HTTPS?

build.log

2020-03-20 11:36:51 (14.2 MB/s) - ‘download/jboss-eap-6.3.3-src.zip.md5’ saved [                                                     58/58]

=== Patch ===
patching file work/jboss-eap-6.3-src/pom.xml
Hunk #1 succeeded at 125 with fuzz 2.
=== Main Maven build ===
./tools/maven/bin/mvn -s tools/maven/conf/settings.xml install -Dts.smoke  -Dski                                                     pTests -Drelease=true
[INFO] Scanning for projects...
Downloading: https://maven.repository.redhat.com/ga/org/jboss/jboss-parent/11-re                                                     dhat-1/jboss-parent-11-redhat-1.pom
Downloaded: https://maven.repository.redhat.com/ga/org/jboss/jboss-parent/11-red                                                     hat-1/jboss-parent-11-redhat-1.pom (31 KB at 32.8 KB/sec)
Downloading: https://maven.repository.redhat.com/ga/org/apache/felix/maven-bundl                                                     e-plugin/2.3.7/maven-bundle-plugin-2.3.7.pom
Downloading: http://repo.maven.apache.org/maven2/org/apache/felix/maven-bundle-p                                                     lugin/2.3.7/maven-bundle-plugin-2.3.7.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.jboss.as:jboss-as-parent:7.4.3.Final-redhat-SNAPSHOT (                                                     /opt/jboss/eap-build/work/jboss-eap-6.3-src/pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.apache.felix:maven-bundle-                                                     plugin:2.3.7 or one of its dependencies could not be resolved: Failed to collect                                                      dependencies for org.apache.felix:maven-bundle-plugin:jar:2.3.7 (): Failed to r                                                     ead artifact descriptor for org.apache.felix:maven-bundle-plugin:jar:2.3.7: Coul                                                     d not transfer artifact org.apache.felix:maven-bundle-plugin:pom:2.3.7 from/to c                                                     entral (http://repo.maven.apache.org/maven2): Failed to transfer file: http://re                                                     po.maven.apache.org/maven2/org/apache/felix/maven-bundle-plugin/2.3.7/maven-bund                                                     le-plugin-2.3.7.pom. Return code is: 501, ReasonPhrase:HTTPS Required. -> [Help                                                      2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit                                                     ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea                                                     d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildin                                                     gException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginResoluti                                                     onException

**Comment by hasalex** [comment]
This problem is supposed to be fixed. See merge request #137.
Can you check that you pulled the latest version, please ?

**Comment by sanindd** [comment]
> Эта проблема должна быть решена с помощью запроса на слияние [# 137](https://github.com/hasalex/eap-build/pull/137) .
> Можете ли вы проверить, что вытащили последнюю версию, пожалуйста?

**Comment by sanindd** [comment]
> This problem is supposed to be fixed by merge request #137.
> Can you check that you pulled the latest version, please ?

Yes, I'm downloading the latest version. 
[build.log](https://github.com/hasalex/eap-build/files/4377347/build.log)

I tried to build other versions and everything is fine with them.

**Comment by hasalex** [comment]
OK, that's weird. Let's investigate a bit further.

How did you download the latest version ? With git, wget,...

**Comment by sanindd** [comment]
Yes i use git.
[root@localhost ~]# git clone git://github.com/hasalex/eap-build.git
Cloning into 'eap-build'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 793 (delta 0), reused 0 (delta 0), pack-reused 788
Receiving objects: 100% (793/793), 141.69 KiB | 0 bytes/s, done.
Resolving deltas: 100% (471/471), done.

**Comment by hasalex** [comment]
OK, I think that I've found what causes the issue.
There's no _pluginRepository_ in the settings.xml file.
EAP 6.3.x uses Maven 3.0, which uses maven central as default _pluginRepository_ (http).
EAP 6.4.x uses Maven 3.2, which uses the _repository_ configuration (https).

I'll make more tests, and some cleaning in the settings, and if it's OK, I'll release the fix.

**Comment by hasalex** [comment]
It should be fixed.
@sanindd, could test with the last commit, please ?

**Comment by sanindd** [comment]
Yes build done. Thank you very much!
