### ISSUE TITLE
Build docker images

### ISSUE THREAD

**Issue by hasalex** [hasalex/eap-build#169]
Build images based on Debian or CentOS
Use different versions of JDK, at least 8 and 11.

First attempts in [docker branch](../tree/docker)

**Comment by hasalex** [comment]
OpenJDK 8 package is not available anymore on recent Debian.

Workarounds :

- install OpenJDK manually,
- install Adoptium distro of OpenJDK,
- use Zulu docker images,
- ...

Trying with **azul/zulu-openjdk-centos** and **azul/zulu-openjdk-debian** base images.

**Comment by hasalex** [comment]
Issues had been reported on FreeBSD.
Having something to test the build on FreeBSD would be nice.

As we cannot build FreeBSD based images, we should test the build on a virtual machine.

Solution : use **Vagrant**

**Comment by fcorneli** [comment]
Gave it a quick spin on FreeBSD. Seems like the default `xmlstarlet` install cannot be found. Weird...

**Comment by hasalex** [comment]
@fcorneli Yes, the executable for xmlstarlet is `xml`. That's why I've added an alias :

```
    echo "alias xmlstarlet='xml'" >> /home/vagrant/.bashrc
```

**Comment by fcorneli** [comment]
yeah... I didn't notice your `docker` branch first...

**Comment by hasalex** [comment]
Images with alpine added
