### ISSUE TITLE
jboss-eap-6.3.3-full-maven-repository.zip failed to download

### ISSUE THREAD

**Issue by wapsi** [hasalex/eap-build#44]
http://maven.repository.redhat.com/techpreview/eap6/6.3.3/jboss-eap-6.3.3-full-maven-repository.zip link redirects automatically to this page: https://access.redhat.com/maven-repository and the download fails (or it downloads the HTML page and hash checksumming fails of course).

Has RedHat changed their site's directory structure or has they removed that jboss-eap-X.X.X-full-maven-repository.zip? Is there any fix for this issue?

**Comment by hasalex** [comment]
It seems that RedHat has closed the access to the zip versions of their maven repos. Sad. There's still an online version of the repo, but the build will be really long with it. It's the only solution I'm seeing for the moment. I'll try it.

**Comment by wapsi** [comment]
I asked this from RedHat and here's ther answer:

The full zips are available from the Customer support portal. It was a mistake they were available from inside the maven repository.

All supported EAP artifacts are available from the techpreview/all location.

**Comment by hasalex** [comment]
I changed the build in order to use the online repository. Could you pull & test ?

**Comment by wapsi** [comment]
It's not building:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (generate-configs) on project jboss-as-build: Execution generate-configs of goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run failed: Plugin org.apache.maven.plugins:maven-antrun-plugin:1.7 or one of its dependencies could not be resolved: Failure to find org.slf4j:slf4j-simple:jar:1.7.2.redhat-3 in https://maven.repository.redhat.com/techpreview/all/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-eap-maven-plugin-repository has elapsed or updates are forced -> [Help 1]

I don't know why it's seeking for slf4j-simple version 1.7.2.redhat-3 because in http://maven.repository.redhat.com/techpreview/all/org/slf4j/slf4j-simple/ the most recent version is 1.7.2.redhat-2. Even in earlyaccess repo (https://maven.repository.redhat.com/earlyaccess/all/org/slf4j/slf4j-simple/) there isn't version 1.7.2.redhat-3.

**Comment by hasalex** [comment]
Works for the latest versions. Still some tests and work for the latest versions.

**Comment by hasalex** [comment]
Build won't work anymore for versions 6.0 and 6.1, because we need to patch files in the repo. Could be possible with a pre-downloaded zip repo, but does it worth the effort ? IMHO, No. I'll limit support for 6.2+.
