### ISSUE TITLE
asterisk in md5sum on cygwin

### ISSUE THREAD

**Issue by tkSimon** [hasalex/eap-build#46]
Output produced by cygwin md5sum has one space and an asterisk ' *' as separator.
md5 files in this repo have double space, so the checksum verification fails.
This is because md5sum on cygwin default to binary mode, which causes the separator to include the asterisk, as mentioned here: http://lists.gnu.org/archive/html/bug-coreutils/2009-03/msg00376.html

I see 3 solutions:
1. Add `sed 's/ \*/  /'` to the command that generates and compares the checksum. This would also require sed to be present on linux hosts for the build script not to fail.
2. Add a check for cygwin, and only use above `sed` snippet there. This would have the least impact.
3. Change everything to default to md5sum binary mode. Probably the biggest change.

What do you think would be the best solution?

**Comment by hasalex** [comment]
I don't know anything on cygwin, but it would be nice to support it. What about a Pull Request ?

**Comment by tkSimon** [comment]
Do you prefer any of the three possible solutions over the others?

**Comment by hasalex** [comment]
For the moment, solution 2 is probably the safer. Just like in your commit 2c03732d, except that I would prefer a flatter group of conditions. Something like :
```
   iif uname|grep -i cygwin
    then
      ...
   elif command -v md5sum >/dev/null
   then
      ...
    # MacOS
    elif command -v md5 >/dev/null
    then
      ...
    else
      ...
    fi
```
