### ISSUE TITLE
Error compiling 6.4.0

### ISSUE THREAD

**Issue by visik7** [hasalex/eap-build#47]
I got the following error right now:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (generate-configs) on project jboss-as-build: Execution generate-configs of goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run failed: Plugin org.apache.maven.plugins:maven-antrun-plugin:1.7 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.jboss:jandex:jar:1.2.2.Final-redhat-1, org.slf4j:slf4j-api:jar:1.7.2.redhat-3: Could not find artifact org.jboss:jandex:jar:1.2.2.Final-redhat-1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

What Can I do ?

**Comment by hasalex** [comment]
It's a bug ! I'll fix the patch. 
If you want to build eap before the fix, it's quite simple : launch the build, wait until it fails, and launch it a second time. The second try should work.

**Comment by hasalex** [comment]
Bug should be fixed. Tell me.

**Comment by visik7** [comment]
Confirm
