### ISSUE TITLE
7.0.0-beta

### ISSUE THREAD

**Issue by fcorneli** [hasalex/eap-build#61]
http://ftp.redhat.com/pub/redhat/jboss/eap/7.0.0-beta/en/source/

**Comment by hasalex** [comment]
Working on it. But what a mess ! A lot of broken dependendies, starting with wildfly-core.

**Comment by hasalex** [comment]
Found my mistake : have to use the early access repository (https://maven.repository.redhat.com/earlyaccess)

**Comment by hasalex** [comment]
Just push a commit for this. A first attempt.
The stuff is a bit more difficult because of the split of wildfly and the new wildfly-core. 
We will probably have to change our point of view on the build. Maybe we should re-build wildfly-core first.

**Comment by fcorneli** [comment]
Tested 7.0.0-beta. Thanks for the patching.
