### ISSUE TITLE
Jboss-eap-7.0.0-beta does not build, missing dependecy (org.wildfly.core:wildfly-core-feature-pack:zip:2.0.3.Final-redhat-1)

### ISSUE THREAD

**Issue by rvsoni** [hasalex/eap-build#68]
Jboss-eap-7.0.0-beta build failed on WildFly: Servlet Feature Pack module, 
missing dependency "org.wildfly.core:wildfly-core-feature-pack:zip:2.0.3.Final-redhat-1"

[ERROR] Failed to execute goal on project wildfly-servlet-feature-pack: Could not resolve dependencies for project org.wildfly:wildfly-servlet-feature-pack:pom:10.0.0.CR6-redhat-1: Could not find artifact org.wildfly.core:wildfly-core-feature-pack:zip:2.0.3.Final-redhat-1 in jboss-eap 

see attached logs for more complete details.
[build.log.txt](https://github.com/hasalex/eap-build/files/95932/build.log.txt)

Fix for this issue:

     @@ -217,7 +217,8 @@
              <version.org.syslog4j>0.9.30</version.org.syslog4j>
              <version.org.wildfly.build-tools>1.1.0.Final</version.org.wildfly.build-tools>
              <version.org.wildfly.checkstyle-config>1.0.4.Final</version.org.wildfly.checkstyle-config>
     -        <version.org.wildfly.core>2.0.3.Final-redhat-1</version.org.wildfly.core>
     +        <version.org.wildfly.core>2.0.3.Final</version.org.wildfly.core>
     +        <version.org.wildfly.core.test>2.0.3.Final</version.org.wildfly.core.test>
              <version.org.wildfly.arquillian>1.0.2.Final</version.org.wildfly.arquillian>
              <version.org.yaml.snakeyaml>1.15.0.redhat-1</version.org.yaml.snakeyaml>
              <version.sun.jaxb>2.2.11.redhat-2</version.sun.jaxb>

**Comment by hasalex** [comment]
That's ugly. I don't have the same behavior. I'll have a look.

**Comment by hasalex** [comment]
In the 'build_core' function, could you echo the values of $CORE_EAP_VERSION and $CORE_PUBLIC_VERSION ?

**Comment by rvsoni** [comment]
Output of $CORE_EAP_VERSION and $CORE_PUBLIC_VERSION  are as below

CORE_EAP_VERSION=2.0.3.Final-redhat-1
CORE_PUBLIC_VERSION=2.0.3.Final

Issue is in building wildfly-core-feature-pack on maven build process, it produce artifacts on name of "wildfly-core-feature-pack-2.0.3.Final.zip" not with name of "wildfly-core-feature-pack-2.0.3.Final-redhat-1.zip" so JBoss build process does not able to find it from m2 repo.

see below logs from build.log file.

[INFO] Installing /home/ravi.soni/git/eap-build/work/wildfly-core-2.0.3.Final/core-feature-pack/pom.xml to /home/ravi.soni/.m2/repository/org/wildfly/core/wildfly-core-feature-pack/2.0.3.Final/wildfly-core-feature-pack-2.0.3.Final.pom
[INFO] Installing /home/ravi.soni/git/eap-build/work/wildfly-core-2.0.3.Final/core-feature-pack/target/wildfly-core-feature-pack-2.0.3.Final.zip to /home/ravi.soni/.m2/repository/org/wildfly/core/wildfly-core-feature-pack/2.0.3.Final/wildfly-core-feature-pack-2.0.3.Final.zip

Attached console logs also.

[build-console-log.txt](https://github.com/hasalex/eap-build/files/96191/build-console-log.txt)

[m2-layout-wildfly-core-feature-pack.txt](https://github.com/hasalex/eap-build/files/96240/m2-layout-wildfly-core-feature-pack.txt)

**Comment by hasalex** [comment]
The problem may be the version of maven. In the 'build_core' function, the global mvn is used. You may have a different version compared to mine.
I have to change the script so that it uses the local maven.
I'll come back soon...

**Comment by hasalex** [comment]
Fix pushed. Try it and tell me.

**Comment by hasalex** [comment]
Still failing on travis

**Comment by rvsoni** [comment]
Its looks now, issue in Maven version i guess, i already set M2_HOME

**Comment by hasalex** [comment]
Yes, it works on Travis too. Latest fix was just a typo, when downloading a pom.xml file.
I'm surprised that $M2_HOME has an impact on the build. We are supposed to use a local version of maven. I'll investigate on that.

**Comment by hasalex** [comment]
BTW, thank you for opening the issue.

**Comment by hasalex** [comment]
Some changes are expected on this subject for the final version : https://issues.jboss.org/browse/JBEAP-2813
