### ISSUE TITLE
JBoss EAP 7.0.1 available

### ISSUE THREAD

**Issue by william-shuman** [hasalex/eap-build#80]
JBoss EAP 7.0.1 is available, but unfortunately the sources for wildfly-core-parent are not published at the same place as they were for 7.0.0 

https://maven.repository.redhat.com/earlyaccess/all/org/wildfly/core/wildfly-core-parent/2.1.6.Final-redhat-1/

I've commented on an issue on jboss.org (https://issues.jboss.org/browse/JBEAP-2813), but not sure if it will accomplish much...

**Comment by rgorosito** [comment]
I opened a new issue; https://issues.jboss.org/browse/JBEAP-5576 . The fix is targeted for release 7.1.0

**Comment by william-shuman** [comment]
Looks like your issue was closed with "Won't Fix"

**Comment by malys** [comment]
The official answer of Redhat is: 

> 

    Not all required artifacts are available in supplied EAP 6 Maven Repository to build EAP 6 and running full testsuite, hence the version number of missing artifacts needs to be patched to point to artifacts in public repositories

> 

from [Redhat portal](https://access.redhat.com/solutions/126683).

We need to patch 7.0.x source code to execute the build.

Currently, 7.0.2 is available.

**Comment by hasalex** [comment]
That's what was done for 7.0-beta. 
But I'm not OK with the answer : JBoss EAP is under LGPL, the source code should be published.

**Comment by hasalex** [comment]
Fixed with PR #83
