### ISSUE TITLE
Build fails, cannot find symbol (variable SASL_PROTOCOL)

### ISSUE THREAD

**Issue by beattidp** [hasalex/eap-build#81]
I have tried several times in past weeks, different version, but still seeing this.
Again today:

`$ ./build-eap.sh 6.4.9`

. . .

`$ tail work/build.log` 
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jboss-as-protocol: Compilation failure`
`[ERROR] /Volumes/shared/github/hasalex/eap-build_6.4.9/work/jboss-eap-6.4-src/protocol/src/main/java/org/jboss/as/protocol/ProtocolConnectionUtils.java:[155,36] cannot find symbol`
`[ERROR] symbol:   variable SASL_PROTOCOL`
`[ERROR] location: class org.jboss.remoting3.RemotingOptions`

Environment is Mac, JDK 8.

`$ uname -a`
`Darwin mac.lan.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64`

`$ javac -version`
`javac 1.8.0_51`

**Comment by hasalex** [comment]
Hi,
I've tried again on a MacOS, and it works.
My OS and my JDK are younger, but I don't think that it could be the reason of the failure.
Have you tried to run the build with an empty maven repository ?

**Comment by beattidp** [comment]
I made a local folder inside the project tree.

`$ mkdir -p m2/repository`

Then added at top of build-eap.sh as follows.

`export MAVEN_OPTS="$MAVEN_OPTS -Dmaven.repo.local=/Volumes/shared/github/hasalex/eap-build_6.4.9/m2/repository"`


And confirmed (from separate console) this new blank directory is receiving libraries.

`$ ls m2/repository/`
`antlr/                    commons-collections/      log4j/`
`backport-util-concurrent/ commons-digester/         nekohtml/`
`biz/                      commons-httpclient/       net/`
`classworlds/              commons-io/               org/`
`com/                      commons-lang/             oro/`
`commons-beanutils/        commons-logging/          regexp/`
`commons-cli/              commons-validator/        xerces/`
`commons-codec/            junit/                    xml-apis/`

But, same result; **cannot find symbol:   variable SASL_PROTOCOL**
Perhaps it's an OpenJDK 8 issue -- as if source is somehow not
being parsed properly for these static definitions. (Maybe that
sounds crazy.)  I see the definition in [the source file in GitHub](https://github.com/jboss-remoting/jboss-remoting/blob/master/src/main/java/org/jboss/remoting3/RemotingOptions.java#L205),
and I assume this SASL_PROTOCOL has been defined for some time.

**Comment by hasalex** [comment]
I didn't know OpenJDK on MacOS. Where can I find it ?

**Comment by AlexBaranowski** [comment]
I don't know if it helps. But build with 
```bash
java -verion
openjdk version "1.8.0_101"
``` 
works fine on Scientific Linux 7.
You might try to use http://www.jenv.be/ to switch between different Java environments. And determine if it's really jdk fault.

**Comment by beattidp** [comment]
Yes 8u101 is very recent. I should perhaps try the latest .
My source of OpenJDK for a long time now is Azul Systems.
I see they have 8u102 posted there. (for Win, Mac, Linux;
a.k.a. Zulu. http://www.azul.com/downloads/zulu/ )

**Comment by hasalex** [comment]
Zulu on MacOS is a good idea. 
I've tried with versions 1.8.0_102 and 1.8.0_65. The build works fine with both.
Version 1.8.0_51 is no more available on the web site.
