### ISSUE TITLE
Build fails on mac

### ISSUE THREAD

**Issue by Castafiore** [hasalex/eap-build#91]
=== Patch ===
patching file work/jboss-eap-6.3-src/pom.xml
Hunk #1 succeeded at 125 with fuzz 2.
=== Main Maven build ===
./build.sh: line 105: ulimit: open files: cannot modify limit: Invalid argument
build.sh: Could not set maximum file descriptor limit: unlimited
./tools/maven/bin/mvn -s tools/maven/conf/settings.xml install -Dts.smoke  -DskipTests -Drelease=true
[INFO] Scanning for projects...
Downloading: https://maven.repository.redhat.com/ga/org/jboss/jboss-parent/11-redhat-1/jboss-parent-11-redhat-1.pom

[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.jboss.as:jboss-as-parent:7.4.3.Final-redhat-SNAPSHOT (/Users/tyang073/Documents/Projects/eap-build/work/jboss-eap-6.3-src/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not transfer artifact org.jboss:jboss-parent:pom:11-redhat-1 from/to jboss-eap (https://maven.repository.redhat.com/ga/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by hasalex** [comment]
Looks like you have a problem with your truststore.

Could you try this command and tell me if you get something ?
`keytool -list -v -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit | grep DE:28:F4:A4:FF:E5:B9:2F:A3:C5:03:D1:A3:49:A7:F9:96:2A:82:12`

**Comment by hasalex** [comment]
Hi, 
Any update on this issue ?
Can I close it ?

**Comment by fcorneli** [comment]
I recently did build on a Mac OS X. No problem.
