### ISSUE TITLE
Support to eap 7.0.4 missing

### ISSUE THREAD

**Issue by cgaraujo** [hasalex/eap-build#92]
Could you please give support to last eap version (7.0.4)?

**Comment by wshuman3** [comment]
its there in the eap7 branch

**Comment by cgaraujo** [comment]
Perfect. Thanks.

**Comment by hasalex** [comment]
The build process has changed a lot in the eap7. I would like to test it with a 7.1 version to be sure that it is the right way.
After that, I'll merge the branch into master.
