### ISSUE TITLE
Version 7.1.0

### ISSUE THREAD

**Issue by fcorneli** [hasalex/eap-build#95]
FYI...
http://ftp.redhat.com/pub/redhat/jboss/eap/7.1.0-alpha/en/source/

**Comment by hasalex** [comment]
Thanks Frank.
I've tried to build it but it failed. The source is not provided for wildfly-core.
I'll wait the final version and then only I'll see if I've to change the build.

**Comment by fcorneli** [comment]
EAP 7 probably needs to mature some more...

**Comment by hasalex** [comment]
Yes. We should probably wait until the final version.

**Comment by fcorneli** [comment]
7.1.0 is available:
http://ftp.redhat.com/pub/redhat/jboss/eap/7.1.0/en/source/

**Comment by hasalex** [comment]
Thanks Frank.
I'll have a look at that.

**Comment by hasalex** [comment]
This work is in progress.
No new core feature pack has been published in the redhat repo. I switch to nearest one in the maven central repo.
Then there's some additional issues with a missing migration feature pack.

**Comment by hasalex** [comment]
Build of version 7.1.0 is ready in branch eap7.
Next step : put the support of 7.x in master.
