### ISSUE TITLE
7.0.6 available but build fails

### ISSUE THREAD

**Issue by wshuman3** [hasalex/eap-build#97]
I've tried building 7.0.6, but there is a dependency issue within the feature pack build with cxf and commons-logging.  I haven't had time to dig into it yet.

**Comment by hasalex** [comment]
Maybe not a dependency issue, but rather a problem when building wildfly core. 
The build does not generate the org.apache.commons.logging module.
I'll investigate.

**Comment by hasalex** [comment]
I can confirm that the issue is related to a lacking module.
I've found a workaround.
